name: FocusMonitoring
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
      - mediapipe==0.10.20
      - numpy==1.26.4
      - opencv-python==4.10.0.84
      - PyOpenGL==3.1.7
      - streamlit==1.41.1
      - watchdog==6.0.0
